print("Please enter the number of lives: ")
health = int(input())
print("Please enter the energy level: ")
energy = int(input())
print("Please enter the shield level: ")
shield = int(input())
print("Health has been set")
print("Lives", "\u2665"*health)
print("Energy:","\u2666"*energy)
print("Shields", "\u2665"*shield)
